// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctyKoS2gGuu9cqq80tDGwtBT2k_K663g',
    appId: '1:1007812916712:android:5ea44633f7d1a0769ce05d',
    messagingSenderId: '1007812916712',
    projectId: 'allowance-app-a2963',
    storageBucket: 'allowance-app-a2963.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjuKK3tcv0jttLyp7PLDr1USl4M69BhY',
    appId: '1:1007812916712:ios:4985d87ba7f2fdf29ce05d',
    messagingSenderId: '1007812916712',
    projectId: 'allowance-app-a2963',
    storageBucket: 'allowance-app-a2963.appspot.com',
    iosBundleId: 'nakajimamasao.appstudio.allowancetracker',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6TaLatGZ4x_eok6xPM11v6UANrsbrwE',
    appId: '1:1007812916712:web:85ae8fe7073508559ce05d',
    messagingSenderId: '1007812916712',
    projectId: 'allowance-app-a2963',
    authDomain: 'allowance-app-a2963.firebaseapp.com',
    storageBucket: 'allowance-app-a2963.appspot.com',
    measurementId: 'G-JV8B7SS2M7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSjuKK3tcv0jttLyp7PLDr1USl4M69BhY',
    appId: '1:1007812916712:ios:ed8f2126feaa6cf69ce05d',
    messagingSenderId: '1007812916712',
    projectId: 'allowance-app-a2963',
    storageBucket: 'allowance-app-a2963.appspot.com',
    iosBundleId: 'nakajimamasao.appstudio.allowancetracker.kawaiiAllowanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa6TaLatGZ4x_eok6xPM11v6UANrsbrwE',
    appId: '1:1007812916712:web:8d4efa9b60cfed269ce05d',
    messagingSenderId: '1007812916712',
    projectId: 'allowance-app-a2963',
    authDomain: 'allowance-app-a2963.firebaseapp.com',
    storageBucket: 'allowance-app-a2963.appspot.com',
    measurementId: 'G-71Q0142ZP5',
  );
}
